import { getPortfolioData } from "@/app/dashboard/portfolio/actions";
import { notFound } from "next/navigation";
import { Github, ExternalLink, Code2, Briefcase, Activity, Zap, Box, Brain, Cpu, Database, Layout, ShieldCheck, Mail, Send, Terminal, Award } from "lucide-react";
import { JobCompatibilityChart } from "@/components/ui/job-compatibility-chart";
import { NeuralBg } from "@/components/ui/neural-bg";
import { ShareIdentity } from "@/components/ui/share-identity";
import { PremiumCard } from "@/components/ui/premium-card";
import { CertificatesList } from "@/components/ui/certificates-list";
import { LiveIndicator } from "@/components/ui/live-indicator";
import { TypingText } from "@/components/ui/typing-text";

import { Metadata, ResolvingMetadata } from "next";

type Props = {
    params: { username: string }
};

export async function generateMetadata(
    { params }: Props,
    parent: ResolvingMetadata
): Promise<Metadata> {
    const p = await params;
    const username = p.username;

    return {
        title: `${username}'s Developer Portfolio | DevRoast.ai`,
        description: `Explore ${username}'s top tech stacks, career archetype, and AI-roasts on DevRoast.`,
        openGraph: {
            title: `${username}'s AI Developer Portfolio`,
            description: `A next-generation, brutally honest developer portfolio generated by DevRoast.`,
            images: [`/api/og/portfolio/${username}`],
        },
        twitter: {
            card: "summary_large_image",
            title: `${username} - DevRoast AI Profile`,
            description: `Explore my AI-audited code architecture.`,
            images: [`/api/og/portfolio/${username}`],
        },
    };
}

export default async function PublicPortfolioPage({ params }: Props) {
    const p = await params;
    const { username } = p;

    const res = await getPortfolioData(username);
    if (!res.success || !res.portfolio) {
        notFound();
    }

    const { portfolio, compatibility } = res;

    const heroData = portfolio.hero as any;
    const hero = { tagline: heroData.tagline, about: heroData.about };
    const vibe = heroData.vibe || {};
    const roast = heroData.roast || "";
    const achievements = heroData.achievements || [];
    const roadmap = heroData.roadmap || [];
    const techStack = heroData.techStack || null;
    const dnaStats = heroData.dnaStats || [];
    const status = heroData.status || "Synchronized";
    const contactEmail = heroData.contactEmail || `hello+${username}@${username}.dev`;
    
    const skills = (portfolio as any).skills as string[] || [];
    const projects = (portfolio as any).projects as any[] || [];
    const certificates = (portfolio as any).certificates as any[] || [];
    const template = (portfolio as any).template as string || "crucible";

    return (
        <div className={`min-h-screen selection:bg-primary/30 ${
            template === 'neon' ? 'bg-[#000103]' : 
            template === 'minimalist' ? 'bg-[#fafafa] text-zinc-900' : 
            template === 'cyberpunk' ? 'bg-[#facc15] text-black font-mono' :
            template === 'blueprint' ? 'bg-[#003366] text-blue-100 font-mono' :
            template === 'hacker' ? 'bg-black text-emerald-400 font-mono' :
            template === 'prism' ? 'bg-[#030014] text-white/90' :
            template === 'aura' ? 'bg-[#080112] text-violet-100/90' :
            'bg-[#050505] text-zinc-100'
        }`}>
            {/* Background Effects */}
            {template === 'neon' && (
                <div className="fixed inset-0 pointer-events-none">
                    <NeuralBg />
                    <div className="absolute top-0 left-1/4 w-[500px] h-[500px] bg-primary/20 blur-[150px] rounded-full" />
                    <div className="absolute bottom-0 right-1/4 w-[500px] h-[500px] bg-accent/10 blur-[150px] rounded-full" />
                </div>
            )}
            {template === 'cyberpunk' && (
                <div className="fixed inset-0 pointer-events-none">
                    <div className="absolute inset-0 bg-[repeating-linear-gradient(0deg,rgba(0,0,0,0.05)_0px,rgba(0,0,0,0.05)_1px,transparent_1px,transparent_2px)] bg-[size:100%_4px]" />
                </div>
            )}
            {template === 'blueprint' && (
                <div className="fixed inset-0 pointer-events-none opacity-20">
                    <div className="absolute inset-0 bg-[linear-gradient(rgba(255,255,255,0.1)_1px,transparent_1px),linear-gradient(90deg,rgba(255,255,255,0.1)_1px,transparent_1px)] bg-[size:20px_20px]" />
                    <div className="absolute inset-0 bg-[linear-gradient(rgba(255,255,255,0.05)_2px,transparent_2px),linear-gradient(90deg,rgba(255,255,255,0.05)_2px,transparent_2px)] bg-[size:100px_100px]" />
                </div>
            )}
            {template === 'hacker' && (
                <div className="fixed inset-0 pointer-events-none overflow-hidden opacity-10">
                    <div className="absolute inset-0 bg-[linear-gradient(0deg,rgba(16,185,129,0.1)_50%,transparent_50%)] bg-[size:100%_4px]" />
                </div>
            )}
            {template === 'prism' && (
                <div className="fixed inset-0 pointer-events-none overflow-hidden">
                    <div className="absolute top-[-10%] left-[-10%] w-[50%] h-[50%] bg-fuchsia-500/10 blur-[120px] rounded-full animate-pulse" />
                    <div className="absolute bottom-[-10%] right-[-10%] w-[50%] h-[50%] bg-blue-500/10 blur-[120px] rounded-full" />
                    <div className="absolute top-[20%] right-[-5%] w-[30%] h-[30%] bg-orange-500/10 blur-[100px] rounded-full animate-pulse" />
                </div>
            )}
            {template === 'aura' && (
                <div className="fixed inset-0 pointer-events-none overflow-hidden">
                    <div className="absolute inset-0 bg-[radial-gradient(circle_at_50%_50%,rgba(139,92,246,0.05),transparent_70%)]" />
                    <div className="absolute top-1/4 left-1/2 -translate-x-1/2 w-[800px] h-[800px] bg-violet-600/10 blur-[150px] rounded-full animate-pulse" />
                </div>
            )}

            {/* Layout Wrapper */}
            <div className={`relative z-10 min-h-screen ${
                template === 'hacker' ? 'flex items-center justify-center p-4' : 
                template === 'blueprint' ? 'flex' : ''
            }`}>
                
                {/* BLUEPRINT SIDEBAR LAYOUT */}
                {template === 'blueprint' && (
                    <aside className="w-80 border-r-2 border-dashed border-white/20 h-screen sticky top-0 p-8 space-y-12 shrink-0 hidden md:block bg-blue-950/20 backdrop-blur-sm">
                        <div className="absolute top-0 right-0 h-full w-px bg-white/5 -mr-4" />
                        <div className="absolute top-0 left-0 w-full h-12 border-b border-white/10 flex items-center px-4 text-[10px] font-mono text-white/20 uppercase tracking-[0.5em]">
                            X-Axis Tracking // 001-999
                        </div>
                        <div className="pt-12 space-y-12">
                            <div className="space-y-4">
                                <div className="w-16 h-16 border-2 border-white/20 rounded-full flex items-center justify-center bg-blue-500/10">
                                    <Github className="w-8 h-8" />
                                </div>
                                <h2 className="text-2xl font-black italic tracking-tighter">PROJ-{username.toUpperCase()}</h2>
                                <div className="p-4 bg-white/5 border border-white/10 text-[9px] font-mono leading-relaxed text-blue-300/60 uppercase">
                                    <div className="flex justify-between border-b border-white/5 pb-1 mb-1">
                                        <span>STATUS:</span>
                                        <span className="text-blue-400">ACTIVE_SYNTH</span>
                                    </div>
                                    <div className="flex justify-between">
                                        <span>ORIGIN:</span>
                                        <span>GITHUB_API_V4</span>
                                    </div>
                                </div>
                            </div>
                            <div className="space-y-6">
                                <h3 className="text-[10px] font-bold uppercase tracking-[0.4em] text-white/30 border-l-2 border-blue-400 pl-4">System_Manifest</h3>
                                <div className="flex flex-col gap-3">
                                    {skills.map(skill => (
                                        <div key={skill} className="flex justify-between items-center text-[10px] bg-white/5 px-2 py-1.5 border-l-2 border-transparent hover:border-blue-400 transition-all">
                                            <span className="opacity-60">{skill}</span>
                                            <span className="text-blue-500 font-bold">1.0</span>                                        </div>
                                    ))}
                                </div>
                            </div>
                        </div>
                    </aside>
                )}

                <div className={`
                    ${template === 'hacker' ? 'w-full max-w-5xl h-[85vh] bg-[#050505] border border-emerald-500/40 rounded-sm shadow-[0_0_50px_rgba(16,185,129,0.1)] flex flex-col relative' : 
                      template === 'blueprint' ? 'flex-1 overflow-auto relative bg-[radial-gradient(circle_at_2px_2px,rgba(255,255,255,0.05)_1px,transparent_0)] bg-[size:40px_40px]' : 
                      'max-w-4xl mx-auto px-6 py-24 space-y-32'
                    }
                `}>

                    {/* BLUEPRINT COORDINATE LABELS */}
                    {template === 'blueprint' && (
                        <div className="absolute top-0 left-0 w-full h-full pointer-events-none opacity-20 text-[9px] font-mono uppercase text-white/40">
                            {[...Array(5)].map((_, i) => (
                                <div key={i} className="absolute left-8" style={{ top: `${(i+1)*20}%` }}>REF_{((i+1)*100).toString().padStart(4, '0')}</div>
                            ))}
                        </div>
                    )}
                    
                    {/* HACKER TERMINAL HEADER */}
                    {template === 'hacker' && (
                        <div className="bg-emerald-950/40 border-b border-emerald-500/20 px-6 py-3 flex items-center justify-between">
                            <div className="flex gap-2 shrink-0">
                                <div className="w-3 h-3 rounded-full bg-[#ff5f56]" />
                                <div className="w-3 h-3 rounded-full bg-[#ffbd2e]" />
                                <div className="w-3 h-3 rounded-full bg-[#27c93f]" />
                            </div>
                            <div className="flex-1 flex justify-center px-4">
                                <LiveIndicator status={status} template={template} />
                            </div>
                            <div className="text-[11px] font-mono text-emerald-500/60 font-medium tracking-widest hidden lg:flex items-center gap-2">
                                <Activity className="w-3 h-3 animate-pulse" />
                                DEVROAST SHELL V2.1.0 // {username}
                            </div>
                        </div>
                    )}

                    <div className={`
                        ${template === 'hacker' ? 'flex-1 p-8 overflow-y-auto font-mono scrollbar-hide' : 
                          template === 'blueprint' ? 'p-12 md:p-24 space-y-32' : 
                          'space-y-32'
                        }
                    `}>
                        {/* Hero Section */}
                        <header className={`animate-in fade-in slide-in-from-bottom-8 duration-1000 ${
                            template === 'cyberpunk' ? 'grid md:grid-cols-12 gap-16 items-start' : 'space-y-8'
                        }`}>
                            <div className={`${template === 'cyberpunk' ? 'md:col-span-8' : ''}`}>
                                {template !== 'hacker' && (
                                    <div className="flex justify-start mb-12">
                                        <LiveIndicator status={status} template={template} />
                                    </div>
                                )}
                                <div className={`inline-flex items-center gap-2 px-3 py-1 rounded-full text-sm mb-6 ${
                                    template === 'minimalist' ? 'bg-zinc-100 border border-zinc-200 text-zinc-600' : 
                                    template === 'cyberpunk' ? 'bg-black text-[#facc15] border border-black shadow-[4px_4px_0px_rgba(0,0,0,1)]' :
                                    template === 'blueprint' ? 'bg-white/10 border border-white/20 text-blue-200' :
                                    template === 'hacker' ? 'text-emerald-500 mb-2' :
                                    template === 'prism' ? 'bg-white/5 border border-white/10 backdrop-blur-xl text-fuchsia-300' :
                                    template === 'aura' ? 'bg-violet-900/30 border border-violet-500/30 text-violet-300' :
                                    'bg-white/5 border border-white/10 text-zinc-400'
                                }`}>
                                    <Github className="w-4 h-4" />
                                    <span>@{portfolio.username}</span>
                                </div>
                                
                                <h1 className={`font-black tracking-tighter leading-[1.05] ${
                                    template === 'neon' ? 'text-5xl md:text-8xl text-white drop-shadow-[0_0_15px_rgba(255,255,255,0.3)]' : 
                                    template === 'minimalist' ? 'text-5xl md:text-8xl text-zinc-900 antialiased' : 
                                    template === 'cyberpunk' ? 'text-4xl md:text-7xl text-black bg-white px-4 py-2 uppercase italic shadow-[10px_10px_0px_rgba(0,0,0,1)] -rotate-1 inline-block mb-4' : 
                                    template === 'blueprint' ? 'text-5xl md:text-8xl text-white border-b-4 border-white/30 pb-4' : 
                                    template === 'hacker' ? 'text-4xl md:text-6xl text-emerald-500 mb-8 font-bold' : 
                                    template === 'prism' ? 'text-5xl md:text-8xl bg-gradient-to-r from-fuchsia-300 via-blue-300 to-emerald-300 bg-clip-text text-transparent' : 
                                    template === 'aura' ? 'text-5xl md:text-8xl text-white drop-shadow-[0_0_20px_rgba(139,92,246,0.5)]' : 'text-5xl md:text-8xl'
                                }`}>
                                    {template === 'hacker' ? (
                                        <div className="space-y-4">
                                            <pre className="text-[10px] md:text-xs leading-none opacity-40">
{`   _____               _____                 _   
  |  __ \\             |  __ \\               | |  
  | |  | | ___ _   _  | |__) |___   __ _ ___| |_ 
  | |  | |/ _ \\ \\ / / |  _  // _ \\ / _\` / __| __|
  | |__| |  __/\\ V /  | | \\ \\ (_) | (_| \\__ \\ |_ 
  |_____/ \\___| \\_/   |_|  \\_\\___/ \\__,_|___/\\__|`}
                                            </pre>
                                            <div className="mt-8 flex flex-wrap items-center gap-2">
                                                <div className="flex items-center gap-2 shrink-0">
                                                    <span className="opacity-30">root@</span><span className="text-white">{username}</span><span className="opacity-30">:~$</span> 
                                                </div>
                                                <span className="border-r-4 border-emerald-500 pr-2 break-words">
                                                    <TypingText text={hero?.tagline} speed={40} />
                                                </span>
                                            </div>
                                        </div>
                                    ) : hero?.tagline}
                                </h1>
                                
                                <p className={`text-xl md:text-2xl leading-relaxed mt-8 font-light ${
                                    template === 'minimalist' ? 'text-zinc-600' : 
                                    template === 'cyberpunk' ? 'text-black font-black bg-white/20 p-6 border-l-8 border-black' : 
                                    template === 'blueprint' ? 'text-blue-300 font-mono border-l-2 border-white/20 pl-6' : 
                                    template === 'hacker' ? 'text-emerald-400 font-mono mt-12 bg-emerald-500/5 p-6 border-l-2 border-emerald-500/30' : 
                                    template === 'prism' ? 'text-white/60 font-light' : 
                                    template === 'aura' ? 'text-violet-200/80 font-light italic' : 'text-zinc-400'
                                }`}>
                                    {template === 'hacker' && <span className="text-emerald-500/50 mr-2 mb-4 block text-xs tracking-widest">// START ENCRYPTED BIO</span>}
                                    {template === 'hacker' ? (
                                        <TypingText text={hero?.about} speed={20} delay={hero?.tagline?.length * 40 + 500} />
                                    ) : hero?.about}
                                    {template === 'hacker' && <span className="inline-block w-2.5 h-6 bg-emerald-500 ml-2 animate-pulse align-middle" />}
                                </p>

                                {vibe.title && (
                                    <div className="mt-12 flex flex-col md:flex-row gap-6 items-start md:items-center">
                                        <div className={`px-6 py-3 rounded-2xl border ${
                                            template === 'neon' ? 'bg-indigo-500/10 border-indigo-500/20 text-indigo-400' :
                                            template === 'minimalist' ? 'bg-zinc-900 text-white' :
                                            template === 'cyberpunk' ? 'bg-black text-[#facc15] shadow-[6px_6px_0px_rgba(250,204,21,0.2)]' :
                                            'bg-white/5 border-white/10'
                                        }`}>
                                            <span className="text-[10px] font-black uppercase tracking-[0.3em] block mb-1 opacity-50">Career Archetype</span>
                                            <span className="text-xl font-black italic uppercase tracking-tighter">{vibe.title}</span>
                                        </div>
                                        <div className="flex-1">
                                            <p className={`text-sm font-medium italic border-l-2 border-white/10 pl-4 ${
                                                template === 'minimalist' ? 'text-zinc-500 border-zinc-200' : 'text-zinc-500'
                                            }`}>{vibe.description}</p>
                                        </div>
                                    </div>
                                )}

                                {roast && (
                                    <div className={`mt-8 p-6 border-l-8 ${
                                        template === 'neon' ? 'bg-rose-500/5 border-rose-500/20 text-rose-400' :
                                        template === 'minimalist' ? 'bg-zinc-50 border-zinc-200 text-zinc-500' :
                                        template === 'cyberpunk' ? 'bg-white border-black text-black font-black uppercase italic shadow-[8px_8px_0px_rgba(0,0,0,0.1)]' :
                                        'bg-white/5 border-white/10 text-zinc-400'
                                    } flex gap-4 items-center transition-all hover:scale-[1.01]`}>
                                        <span className={`shrink-0 px-2 py-0.5 rounded text-[10px] font-black uppercase ${
                                            template === 'cyberpunk' ? 'bg-black text-white' : 'bg-current/10'
                                        }`}>Roast</span>
                                        <p className={`${template === 'cyberpunk' ? 'text-xs md:text-sm' : 'text-xs font-mono'}`}>"{roast}"</p>
                                    </div>
                                )}

                                {achievements.length > 0 && (
                                    <div className="mt-12 grid grid-cols-2 md:grid-cols-4 gap-4">
                                        {achievements.map((item: any, i: number) => (
                                            <div key={i} className={`p-4 rounded-2xl border ${
                                                template === 'neon' ? 'bg-white/[0.02] border-white/5' :
                                                template === 'minimalist' ? 'bg-zinc-50 border-zinc-100' :
                                                template === 'cyberpunk' ? 'bg-white border-4 border-black rounded-none shadow-[6px_6px_0px_rgba(0,0,0,1)]' :
                                                'bg-white/5 border-white/10'
                                            }`}>
                                                <span className={`block text-[9px] font-black uppercase tracking-widest mb-1 ${
                                                    template === 'minimalist' ? 'text-zinc-400' : 
                                                    template === 'cyberpunk' ? 'text-black opacity-40' : 'text-zinc-600'
                                                }`}>{item.label}</span>
                                                <span className={`text-2xl font-black tracking-tighter ${
                                                    template === 'prism' ? 'text-blue-400' : 
                                                    template === 'minimalist' ? 'text-zinc-900' :
                                                    template === 'cyberpunk' ? 'text-black' : 'text-white'
                                                }`}>{item.value}</span>
                                            </div>
                                        ))}
                                    </div>
                                )}

                                {/* DNA Stats Section */}
                                {dnaStats.length > 0 && (
                                    <div className="mt-12 flex flex-wrap gap-4">
                                        {dnaStats.map((stat: any, i: number) => (
                                            <div key={i} className={`flex items-center gap-3 px-4 py-2 border rounded-xl transition-all hover:scale-105 ${
                                                template === 'neon' ? 'bg-primary/5 border-primary/20 text-primary' :
                                                template === 'hacker' ? 'border-emerald-500/20 text-emerald-400' :
                                                template === 'cyberpunk' ? 'bg-white border-2 border-black text-black shadow-[4px_4px_0px_rgba(0,0,0,0.1)]' :
                                                'bg-white/5 border-white/10 text-zinc-400'
                                            }`}>
                                                {stat.icon === 'Zap' && <Zap className="w-4 h-4" />}
                                                {stat.icon === 'Box' && <Box className="w-4 h-4" />}
                                                {stat.icon === 'Brain' && <Brain className="w-4 h-4" />}
                                                <div className="flex flex-col">
                                                    <span className={`text-[9px] font-black uppercase tracking-widest opacity-50 ${
                                                        template === 'minimalist' ? 'text-zinc-500' :
                                                        template === 'cyberpunk' ? 'text-black' : ''
                                                    }`}>{stat.label}</span>
                                                    <span className={`text-xs font-bold leading-none ${
                                                        template === 'minimalist' ? 'text-zinc-900' : ''
                                                    }`}>{stat.value}</span>
                                                </div>
                                            </div>
                                        ))}
                                    </div>
                                )}
                            </div>

                            {/* CYBERPUNK SIDEBAR SKILLS */}
                            {template === 'cyberpunk' && (
                                <aside className="md:col-span-4 self-start space-y-8 relative z-20 md:pl-8 border-l-4 border-black/5">
                                    <div className="bg-black p-4 text-white -rotate-2 transform shadow-[8px_8px_0px_rgba(0,0,0,0.1)]">
                                        <h3 className="font-black italic uppercase tracking-tighter text-xl underline decoration-4 decoration-[#facc15]">Vitals //</h3>
                                        <div className="mt-4 space-y-2 text-xs">
                                            {skills.map(s => (
                                                <div key={s} className="flex justify-between items-center border-b border-white/20 pb-1">
                                                    <span>{s}</span>
                                                    <span className="font-black text-[#facc15]">100%</span>
                                                </div>
                                            ))}
                                        </div>
                                    </div>
                                    <div className="bg-white p-3 border-4 border-black font-black text-center text-sm md:text-base uppercase tracking-tighter hover:bg-[#facc15] transition-colors cursor-crosshair shadow-[6px_6px_0px_rgba(0,0,0,1)] rotate-1 hover:rotate-0 transition-transform active:translate-x-1 active:translate-y-1 active:shadow-none overflow-hidden whitespace-nowrap">
                                        Hire_Me.exe
                                    </div>
                                </aside>
                            )}

                            {template !== 'cyberpunk' && (
                                <div className="pt-4 flex flex-wrap gap-2 text-sm uppercase tracking-widest font-bold">
                                    {skills.map((skill: string) => (
                                        <span key={skill} className={`px-4 py-2 border transition-all duration-300 ${
                                            template === 'neon' ? 'text-primary border-primary/40 bg-primary/5 hover:bg-primary/20 hover:border-primary' : 
                                            template === 'minimalist' ? 'text-zinc-800 border-zinc-200 bg-white hover:bg-zinc-50' : 
                                            template === 'blueprint' ? 'text-white border-white/40 bg-white/5 hover:bg-white/20' :
                                            template === 'hacker' ? 'border-emerald-500/30 text-emerald-400 hover:bg-emerald-500/10' :
                                            template === 'prism' ? 'bg-white/5 border-white/10 hover:bg-white/20 backdrop-blur-md text-white/80 rounded-full px-6' :
                                            template === 'aura' ? 'bg-violet-900/20 border-violet-500/30 text-violet-200 hover:bg-violet-500/20 rounded-lg' :
                                            'text-primary bg-primary/10 border-primary/20 hover:border-primary/50'
                                        }`}>
                                            {skill}
                                        </span>
                                    ))}
                                </div>
                            )}

                                {techStack && (
                                    <div className={`mt-24 space-y-12 ${template === 'cyberpunk' ? 'md:col-span-12' : ''}`}>
                                        <h3 className={`text-[10px] font-black uppercase tracking-[0.4em] flex items-center gap-2 ${
                                            template === 'cyberpunk' ? 'text-black opacity-40' : 'text-zinc-600'
                                        }`}>
                                            <Cpu className="w-3 h-3" /> Engineering_Matrix // Tech Depth
                                        </h3>
                                        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
                                            {Object.entries(techStack).map(([category, items]: [string, any]) => (
                                                <div key={category} className={`p-6 border flex flex-col gap-4 group transition-all ${
                                                    template === 'neon' ? 'bg-white/[0.02] border-white/5 rounded-[2rem]' :
                                                    template === 'hacker' ? 'border-emerald-500/10 rounded-sm bg-emerald-500/[0.02]' :
                                                    template === 'cyberpunk' ? 'bg-white border-4 border-black rounded-none shadow-[8px_8px_0px_rgba(0,0,0,1)]' :
                                                    'bg-white/5 border-white/10 rounded-2xl'
                                                }`}>
                                                    <div className="flex items-center gap-2 mb-2">
                                                        {category === 'frontend' && <Layout className="w-4 h-4 text-blue-400" />}
                                                        {category === 'backend' && <Database className="w-4 h-4 text-emerald-400" />}
                                                        {category === 'infrastructure' && <ShieldCheck className="w-4 h-4 text-amber-400" />}
                                                        {category === 'devTools' && <Terminal className="w-4 h-4 text-rose-400" />}
                                                        <h4 className={`text-xs font-black uppercase tracking-widest ${
                                                            template === 'minimalist' ? 'text-zinc-900' : 'text-white'
                                                        }`}>{category}</h4>
                                                    </div>
                                                    <div className="flex flex-wrap gap-2">
                                                        {items.map((tech: string) => (
                                                            <span key={tech} className={`text-[10px] font-bold px-2 py-1 rounded-md border ${
                                                                template === 'cyberpunk' ? 'text-black bg-[#facc15]/20 border-black/10' : 'text-zinc-500 bg-white/5 border-white/5'
                                                            }`}>
                                                                {tech}
                                                            </span>
                                                        ))}
                                                    </div>
                                                </div>
                                            ))}
                                        </div>
                                    </div>
                                )}

                                {roadmap.length > 0 && (
                                    <div className={`mt-24 space-y-8 ${template === 'cyberpunk' ? 'md:col-span-12' : ''}`}>
                                        <h3 className={`text-[10px] font-black uppercase tracking-[0.4em] ${
                                            template === 'cyberpunk' ? 'text-black opacity-40' : 'text-zinc-600'
                                        }`}>Growth_Roadmap // 2026-2027</h3>
                                        <div className="grid gap-4">
                                            {roadmap.map((step: any, i: number) => {
                                                const title = typeof step === 'string' ? step : (step.goal || step.phase || "Objective Data");
                                                const subtitle = typeof step === 'object' ? (step.phase && step.goal ? step.phase : "") : "";
                                                
                                                return (
                                                    <div key={i} className={`p-6 border flex gap-6 items-center group transition-all ${
                                                        template === 'neon' ? 'bg-primary/5 border-primary/10 rounded-2xl hover:border-primary/40' :
                                                        template === 'minimalist' ? 'bg-zinc-50 border-zinc-100' :
                                                        template === 'cyberpunk' ? 'bg-black text-white border-none rounded-none shadow-[8px_8px_0px_rgba(255,255,255,0.1)]' :
                                                        'bg-white/5 border-white/10 rounded-xl'
                                                    }`}>
                                                        <span className={`text-4xl font-black italic opacity-20 group-hover:opacity-100 transition-opacity shrink-0 ${
                                                            template === 'prism' ? 'text-fuchsia-400' : 
                                                            template === 'cyberpunk' ? 'text-[#facc15]' : 'text-primary'
                                                        }`}>0{i+1}</span>
                                                        <div className="flex flex-col">
                                                            {subtitle && (
                                                                <span className={`text-[9px] font-black uppercase tracking-widest mb-1 opacity-50 ${
                                                                    template === 'cyberpunk' ? 'text-[#facc15]' : 'text-primary'
                                                                }`}>
                                                                    {subtitle}
                                                                </span>
                                                            )}
                                                            <p className="font-bold tracking-tight text-lg">{title}</p>
                                                        </div>
                                                    </div>
                                                );
                                            })}
                                        </div>
                                    </div>
                                )}
                        </header>

                        {/* Experience Section */}
                        <section className="space-y-6">
                            <h2 className={`text-sm uppercase tracking-widest font-bold flex items-center gap-2 ${
                                template === 'minimalist' ? 'text-zinc-400' : 
                                template === 'cyberpunk' ? 'text-black opacity-30 text-4xl font-black mb-12 block w-full mt-24' : 
                                template === 'blueprint' ? 'text-blue-200 mt-24' : 
                                template === 'hacker' ? 'text-emerald-500/50 mt-24' : 
                                template === 'prism' ? 'text-fuchsia-500/50 mt-24' : 
                                template === 'aura' ? 'text-violet-400/50 mt-24' : 'text-zinc-500'
                            }`}>
                                <Briefcase className="w-4 h-4" />
                                {template === 'cyberpunk' ? 'LEVEL_EXP' : 'Professional Synopsis'}
                            </h2>
                            <div className={`p-8 md:p-12 border relative overflow-hidden group transition-all duration-700 ${
                                template === 'neon' ? 'bg-white/[0.01] border-white/5 hover:border-primary/30 rounded-[2.5rem]' : 
                                template === 'minimalist' ? 'bg-white border-zinc-200 shadow-sm rounded-none' : 
                                template === 'cyberpunk' ? 'bg-white border-8 border-black text-black rounded-none shadow-[20px_20px_0px_rgba(0,0,0,1)] scale-y-105' :
                                template === 'blueprint' ? 'bg-blue-900/30 border-2 border-white/30 rounded-none' :
                                template === 'hacker' ? 'bg-transparent border border-emerald-500/10 p-4' :
                                template === 'prism' ? 'bg-white/[0.03] border-white/10 backdrop-blur-2xl rounded-[3rem] hover:bg-white/[0.05] hover:border-white/20' :
                                template === 'aura' ? 'bg-violet-950/40 border border-violet-500/20 rounded-[2rem] hover:border-violet-500/40' :
                                'bg-white/[0.02] border-white/10 rounded-2xl'
                            }`}>
                                <p className={`text-xl md:text-2xl leading-relaxed relative z-10 ${
                                    template === 'minimalist' ? 'text-zinc-700 font-medium' : 
                                    template === 'cyberpunk' ? 'font-black uppercase tracking-tighter italic' : 
                                    template === 'hacker' ? 'text-emerald-400 text-base opacity-70 font-mono' : 
                                    template === 'aura' ? 'text-violet-100/80 leading-relaxed font-light' : 'text-zinc-300'
                                }`}>
                                    {template === 'hacker' && '$ cat experience.log\n\n'}
                                        {typeof portfolio.experience === 'string' ? (
                                            portfolio.experience.startsWith('{') ? (
                                                (() => {
                                                    try {
                                                        const parsed = JSON.parse(portfolio.experience);
                                                        return parsed.summary || portfolio.experience;
                                                    } catch {
                                                        return portfolio.experience;
                                                    }
                                                })()
                                            ) : portfolio.experience
                                        ) : (
                                            (portfolio.experience as any)?.summary || JSON.stringify(portfolio.experience)
                                        )}
                                </p>
                            </div>

                            {/* JobCompatibilityChart - Hidden in Hacker template for cleaner terminal look */}
                            {compatibility && template !== 'hacker' && (
                                <div className="pt-8">
                                    <JobCompatibilityChart data={compatibility} />
                                </div>
                            )}
                        </section>

                        {/* Certifications Section */}
                        {certificates && certificates.length > 0 && (
                            <section className="space-y-12">
                                <h2 className={`text-sm uppercase tracking-widest font-bold flex items-center gap-2 ${
                                    template === 'minimalist' ? 'text-zinc-400' : 
                                    template === 'cyberpunk' ? 'text-black opacity-30 text-5xl font-black mb-12 block w-full mt-24' : 
                                    template === 'blueprint' ? 'text-blue-300 italic text-xl border-l-4 border-blue-500 pl-4 py-2' : 
                                    template === 'hacker' ? 'text-emerald-500 mt-24 text-lg border-b border-emerald-500/20 pb-4' : 'text-zinc-500'
                                }`}>
                                    <Award className="w-4 h-4" />
                                    {template === 'cyberpunk' ? 'VERIFIED_CREDENTIALS' : template === 'hacker' ? 'sudo decrypt --certs' : 'Verifications & Certifications'}
                                </h2>

                                <CertificatesList certificates={certificates} template={template} />
                            </section>
                        )}

                        {/* Projects Section */}
                        <section className="space-y-12">
                            <h2 className={`text-sm uppercase tracking-widest font-bold flex items-center gap-2 ${
                                template === 'minimalist' ? 'text-zinc-400' : 
                                template === 'cyberpunk' ? 'text-black opacity-30 text-5xl font-black mb-12 block w-full mt-24' : 
                                template === 'blueprint' ? 'text-blue-300 italic text-xl border-l-4 border-blue-500 pl-4 py-2' : 
                                template === 'hacker' ? 'text-emerald-500 mt-24 text-lg border-b border-emerald-500/20 pb-4' : 'text-zinc-500'
                            }`}>
                                <Code2 className="w-4 h-4" />
                                {template === 'cyberpunk' ? 'DEPLOYED_SYSTEMS' : template === 'hacker' ? 'sudo ls -R /projects' : 'Selected Works'}
                            </h2>

                            <div className={`
                                ${template === 'neon' ? 'grid md:grid-cols-2 gap-6' : 
                                  template === 'hacker' ? 'grid md:grid-cols-2 gap-px bg-emerald-500/10 border border-emerald-500/10' : 
                                  template === 'minimalist' ? 'space-y-24' :
                                  'flex flex-col gap-12'
                                }
                            `}>
                                {projects.map((project: any, index: number) => {
                                    return (
                                        <div
                                            key={index}
                                            className="group relative animate-in fade-in slide-in-from-bottom-8 duration-700 fill-mode-both"
                                            style={{ animationDelay: `${500 + index * 150}ms` }}
                                        >
                                            <div className={`relative z-10 p-8 border transition-all duration-500 h-full flex flex-col justify-between ${
                                                template === 'neon' ? 'bg-black border-white/5 group-hover:border-primary/50 group-hover:shadow-[0_0_30px_rgba(255,255,255,0.05)] rounded-[2.5rem]' : 
                                                template === 'minimalist' ? 'bg-transparent border-none p-0 max-w-2xl' : 
                                                template === 'cyberpunk' ? 'bg-white text-black border-4 border-black rounded-none shadow-[15px_15px_0px_rgba(0,0,0,1)] group-hover:translate-x-2 group-hover:-translate-y-2 group-hover:shadow-[25px_25px_0px_rgba(0,0,0,1)]' :
                                                template === 'blueprint' ? 'bg-blue-900/10 border-2 border-dashed border-white/10 rounded-none group-hover:bg-blue-500/5 group-hover:border-white/30' :
                                                template === 'hacker' ? 'bg-[#050505] border-none p-6 group-hover:bg-emerald-500/[0.02]' :
                                                template === 'prism' ? 'bg-white/[0.02] border-white/10 backdrop-blur-3xl rounded-[3rem] group-hover:bg-white/[0.05]' :
                                                'bg-[#0a0a0a] border border-white/10'
                                            }`}>
                                                <div className="space-y-6">
                                                    <div className="flex justify-between items-start">
                                                        <div>
                                                            {template === 'blueprint' && <span className="text-[9px] font-mono text-blue-500 mb-2 block tracking-[0.3em]">REF_ID: MOD_0{index+1}</span>}
                                                            <h3 className={`text-2xl md:text-3xl font-black tracking-tight ${
                                                                template === 'minimalist' ? 'text-zinc-900 text-5xl underline decoration-zinc-100 underline-offset-8' : 
                                                                template === 'cyberpunk' ? 'text-black uppercase italic' : 
                                                                template === 'blueprint' ? 'text-white' : 
                                                                template === 'hacker' ? 'text-emerald-500 text-xl font-mono' : 
                                                                template === 'prism' ? 'text-white' : 
                                                                template === 'minimalist' ? 'text-zinc-900' : 'text-white'
                                                            }`}>
                                                                {template === 'hacker' ? `./${project.title.toLowerCase()}` : project.title}
                                                            </h3>
                                                        </div>
                                                    <div className="flex gap-4 items-center">
                                                        {project.liveUrl && (
                                                            <a href={project.liveUrl} target="_blank" rel="noreferrer" className={`inline-flex items-center gap-2 text-xs font-bold uppercase tracking-[0.2em] transition-all ${
                                                                template === 'minimalist' ? 'text-zinc-900 border-b-2 border-zinc-900' : 
                                                                template === 'cyberpunk' ? 'bg-[#facc15] text-black px-4 py-2 hover:bg-black hover:text-white transition-colors' : 
                                                                template === 'hacker' ? 'text-emerald-500' : 
                                                                template === 'blueprint' ? 'text-white border border-white px-3 py-1' :
                                                                'text-white hover:text-primary transition-colors'
                                                            }`}>
                                                                {template === 'hacker' ? 'LIVE' : 'Live Demo'} <Zap className="w-3 h-3" />
                                                            </a>
                                                        )}
                                                        <a href={project.url || `https://github.com/${portfolio.username}?tab=repositories`} target="_blank" rel="noreferrer" className={`inline-flex items-center gap-2 text-xs font-bold uppercase tracking-[0.2em] transition-all ${
                                                            template === 'minimalist' ? 'text-zinc-300 hover:text-zinc-900' : 
                                                            template === 'cyberpunk' ? 'bg-black text-white px-4 py-2 hover:bg-[#facc15] hover:text-black transition-colors' : 
                                                            template === 'hacker' ? 'text-emerald-500/40 hover:text-emerald-500' : 
                                                            template === 'blueprint' ? 'text-blue-400 hover:text-white border-b border-blue-400' :
                                                            'text-primary hover:text-white'
                                                        }`}>
                                                            {template === 'hacker' ? 'EXEC' : 'Source'} <ExternalLink className="w-3 h-3" />
                                                        </a>
                                                    </div>
                                                    </div>
                                                    <p className={`leading-relaxed text-lg ${
                                                        template === 'minimalist' ? 'text-zinc-500' : 
                                                        template === 'hacker' ? 'text-emerald-400/50 text-xs font-mono' : 
                                                        template === 'prism' ? 'text-white/50 font-light' : 
                                                        template === 'aura' ? 'text-violet-200/50' : 'text-zinc-400'
                                                    }`}>
                                                        {project.description}
                                                    </p>
                                                    {project.impact && (
                                                        <div className={`mt-4 inline-flex items-center gap-2 px-3 py-1.5 rounded-lg text-[10px] font-black uppercase tracking-widest ${
                                                            template === 'neon' ? 'bg-emerald-500/10 text-emerald-400 border border-emerald-500/20' : 
                                                            template === 'minimalist' ? 'bg-zinc-100 text-zinc-600' :
                                                            'bg-white/5 text-zinc-400'
                                                        }`}>
                                                            <Activity className="w-3 h-3" />
                                                            Impact: {project.impact}
                                                        </div>
                                                    )}
                                                </div>
                                                <div className="pt-8 flex flex-wrap gap-2">
                                                    {project.techStacks.map((tech: string) => (
                                                        <span key={tech} className={`px-3 py-1 border text-[9px] font-mono uppercase tracking-widest ${
                                                            template === 'neon' ? 'bg-primary/10 border-primary/30 text-primary rounded-full px-4' : 
                                                            template === 'minimalist' ? 'bg-zinc-50 border-zinc-100 text-zinc-400' : 
                                                            template === 'cyberpunk' ? 'bg-[#facc15] text-black border-2 border-black font-black' :
                                                            template === 'hacker' ? 'text-emerald-500/30' :
                                                            template === 'blueprint' ? 'bg-blue-500/10 border-blue-400/40 text-blue-300' :
                                                            'bg-zinc-900 border-zinc-800 text-zinc-300'
                                                        }`}>
                                                            {tech}
                                                        </span>
                                                    ))}
                                                </div>
                                            </div>
                                        </div>
                                    );
                                })}
                            </div>
                        </section>

                         {/* Hiring Protocol Section */}
                         <section className={`mt-32 p-12 relative overflow-hidden rounded-[3rem] border ${
                                template === 'minimalist' ? 'bg-zinc-900 border-zinc-800' : 'border-white/10 glass-darker'
                             }`}>
                            <div className="absolute top-0 right-0 w-[400px] h-[400px] bg-primary/10 blur-[120px] rounded-full -mr-48 -mt-48" />
                            <div className="relative z-10 text-center space-y-8 max-w-2xl mx-auto">
                                <ShieldCheck className="w-12 h-12 text-primary mx-auto opacity-50" />
                                <h2 className="text-4xl md:text-5xl font-black tracking-tighter text-white">Initiate Hiring_Protocol</h2>
                                <p className="text-zinc-400 text-lg">
                                    Secure the architectural expertise of <span className="text-white font-bold">@{username}</span> for your next mission-critical production. 
                                    High-intensity engineering requires elite coordination.
                                </p>
                                <div className="flex flex-col sm:flex-row gap-4 justify-center pt-8">
                                    <a 
                                        href={`mailto:${contactEmail}?subject=Engagement Request: ${username}`} 
                                        className="inline-flex items-center justify-center gap-2 px-8 py-4 bg-primary text-black font-black uppercase tracking-widest rounded-2xl hover:bg-primary/90 transition-all group"
                                    >
                                        <Send className="w-5 h-5 group-hover:translate-x-1 group-hover:-translate-y-1 transition-transform" />
                                        Request Engagement
                                    </a>
                                    <a 
                                        href={`mailto:${contactEmail}`} 
                                        className="inline-flex items-center justify-center gap-2 px-8 py-4 bg-white/5 border border-white/10 text-white font-black uppercase tracking-widest rounded-2xl hover:bg-white/10 transition-all"
                                    >
                                        <Mail className="w-5 h-5" />
                                        Secure Channel
                                    </a>
                                </div>
                            </div>
                         </section>

                        <ShareIdentity 
                            username={username} 
                            template={template} 
                            roast={roast}
                            score={achievements[0]?.value ? parseFloat(achievements[0].value) : 0}
                        />

                        <footer className={`pt-24 pb-12 text-center text-[10px] text-zinc-600 font-mono uppercase tracking-[0.3em]`}>
                            <p>DNA ANALYSIS: COMPLETE // {username} CORE_ENG READY</p>
                        </footer>
                    </div>
                </div>
            </div>
        </div>
    );
}
